name: llmtester

services:
  llmtester:
    container_name: llmtester
    build: .
    ports:
      - "4444:8000"
    environment:
      DATABASE_URL: sqlite:////app/data/monitor.db
      MONITOR_DATA_DIR: /app/data
    volumes:
      - ./data:/app/data
